==== Setting Path ===== 
 
 {'ARNOLD_TESTSUITE_COMMON': '/home/krishnan/dev/mtoa/testsuite/common', 'MAYA_MODULE_PATH': '/usr/autodesk/arnold/maya2020', 'PYMEL_SKIP_MEL_INIT': '1', 'ADCLMHUB_LOG_DIR': '/home/krishnan/dev/mtoa/build/linux_x86_64/20200000/gcc_debug/testsuite/test_0278', 'MAYA_DISABLE_CIP': '1', 'ADCLMHUB_LOG_LEVEL': 'T', 'ARNOLD_MATERIALX_SEARCH_PATH': '/home/krishnan/dev/mtoa/build/linux_x86_64/20200000/gcc_debug/testsuite/test_0278', 'MAYA_RENDER_DESC_PATH': '/usr/autodesk/arnold/maya2020', 'PATH': '/usr/autodesk/arnold/maya2020/bin;/usr/autodesk/maya2020/bin;/usr/autodesk/arnold/maya2020/lib;/usr/autodesk/arnold/maya2020/plug-ins;/usr/local/bin:/opt/bin:/bin:/usr/bin:.', 'MAYA_DISABLE_CER': '1'}
 
 ==== Exec cmd ==== 
 
/usr/autodesk/maya2020/bin/Render -proj "/home/krishnan/dev/mtoa/build/linux_x86_64/20200000/gcc_debug/testsuite/test_0278" -rd "/home/krishnan/dev/mtoa/build/linux_x86_64/20200000/gcc_debug/testsuite/test_0278" -r arnold -x 160 -y 120  "/home/krishnan/dev/mtoa/build/linux_x86_64/20200000/gcc_debug/testsuite/test_0278/test.ma"
 
 
Starting "/usr/autodesk/maya2020/bin/maya"
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/usr/tmp/runtime-krishnan'
00:00:00   386MB         | log started Wed Feb  3 12:17:06 2021
00:00:00   386MB         | Arnold 6.2.0.0 [cbe64981] linux clang-10.0.1 oiio-2.2.1 osl-1.11.6 vdb-7.1.1 clm-2.0.0.235 rlm-12.4.2 optix-6.6.0 2021/01/21 22:46:22
00:00:00   386MB         | running on ip-192-168-0-45.eu-west-1.compute.internal, pid=19391
00:00:00   386MB         |  2 x Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz (24 cores, 48 logical) with 63847MB
00:00:00   386MB         |  NVIDIA driver version 455.38 (Optix 60700)
00:00:00   386MB         |  GPU 0: Quadro RTX 4000 @ 1545MHz (compute 7.5) with 7982MB (7877MB available) (NVLink:0)
00:00:00   386MB         |  GPU 1: Quadro GP100 @ 1442MHz (compute 6.0) with 16278MB (14750MB available) (NVLink:0)
00:00:00   386MB         |  CentOS Linux 7 (Core), Linux kernel 3.10.0-1062.1.2.el7.x86_64
00:00:00   386MB         |  soft limit for open files raised from 4096 to 4094
00:00:00   386MB         |  
00:00:00   386MB         | loading plugins from /usr/autodesk/arnold/maya2020/plug-ins/../bin/../plugins ...
00:00:00   386MB         |  alembic_proc.so: alembic uses Arnold 6.2.0.0
00:00:00   386MB         |  cryptomatte.so: cryptomatte uses Arnold 6.2.0.0
00:00:00   386MB         |  cryptomatte.so: cryptomatte_filter uses Arnold 6.2.0.0
00:00:00   386MB         |  cryptomatte.so: cryptomatte_manifest_driver uses Arnold 6.2.0.0
00:00:00   389MB         |  usd_proc.so: usd uses Arnold 6.2.0.0
00:00:00   389MB         |  synColor_shaders.so: color_manager_syncolor uses Arnold 6.2.0.0
00:00:00   389MB         | loaded 6 plugins from 4 lib(s) in 0:00.02
Warning: file: /home/krishnan/dev/mtoa/build/linux_x86_64/20200000/gcc_debug/testsuite/test_0278/2020/prefs/filePathEditorRegistryPrefs.mel line 4: filePathEditor: Attribute 'aiImage.filename' is invalid or is not designated 'usedAsFilename'.
Warning: file: /home/krishnan/dev/mtoa/build/linux_x86_64/20200000/gcc_debug/testsuite/test_0278/2020/prefs/filePathEditorRegistryPrefs.mel line 5: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' is invalid or is not designated 'usedAsFilename'.
Warning: file: /home/krishnan/dev/mtoa/build/linux_x86_64/20200000/gcc_debug/testsuite/test_0278/2020/prefs/filePathEditorRegistryPrefs.mel line 7: filePathEditor: Attribute 'aiVolume.filename' is invalid or is not designated 'usedAsFilename'.
Warning: line 1: filePathEditor: Attribute 'aiVolume.filename' and label 'VDB' have been saved already.
00:00:00   393MB WARNING |  unable to load dynamic library /usr/autodesk/arnold/maya2020/procedurals/xgenSpline_procedural.so: libAdskSeExpr.so: cannot open shared object file: No such file or directory
00:00:00   393MB WARNING |  unable to load dynamic library /usr/autodesk/arnold/maya2020/procedurals/xgen_procedural.so: libAdskSeExpr.so: cannot open shared object file: No such file or directory
Warning: line 1: filePathEditor: Attribute 'aiImage.filename' and label 'Image' have been saved already.
Warning: line 1: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' and label 'IES' have been saved already.
libai.so already loaded
Successfully imported python module 'arnold'
Successfully imported python module 'mtoa'
Successfully registered renderer 'arnold'
File read in  3.1 seconds.
Result: /home/krishnan/dev/mtoa/build/linux_x86_64/20200000/gcc_debug/testsuite/test_0278/test.ma
Scene /home/krishnan/dev/mtoa/build/linux_x86_64/20200000/gcc_debug/testsuite/test_0278/test.ma completed.
